### ISSUE TITLE
`Selectable`, `Insertable` and `Updateable` Kysely wrappers

### ISSUE THREAD

**Issue by NazCodeland** [valtyr/prisma-kysely#52]
Hey, thanks for this package! I was reading this page:  https://www.kysely.dev/docs/getting-started and there is a section in there that says 
```typescript
// You should not use the table schema interfaces directly. Instead, you should
// use the `Selectable`, `Insertable` and `Updateable` wrappers. These wrappers
// make sure that the correct types are used in each operation.
export type Person = Selectable<PersonTable>
export type NewPerson = Insertable<PersonTable>
export type EditedPerson = Updateable<PersonTable>
```

I noticed the output file from this pacakge does not include `Selectable<TableName>` , `Insertable<TableName>`, and `Updateable<TableName>` is this not required if you are generating the types from a Prisma schema or is that something we have to manually add to the output file?

thanks in advance

**Comment by valtyr** [comment]
Hey! I'm happy prisma-kysely is of use to you! The wrapper types you're mentioning are actually not related to the inner workings of Kysely itself, but are meant as a convenient way to get normal typescript interfaces from table definitions. Take the example of a table that has rows with different types for insert, update and select. The wrapper types extract only the types that apply to each one of these cases. 

```ts
type TestTable = {
  created_at: ColumnType<Date, string | undefined, never>;
}
```

Here Selectable would return an interface with `created_at` of type Date, Insertable `string | undefined` and Updateable `never`.

In my opinion it's probably out of scope for prisma-kysely to generate these types, since it's a case of adding a single wrapper type. I would be willing to consider a pull request that adds this functionality though, if anyone wants to build it.
